apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - mlflow
            - server
            - --host=0.0.0.0
            - --port=5000
            - --default-artifact-root={{ .Values.s3.bucket }}
            - --backend-store-uri=sqlite:///mlflow.db
            - --dev
          ports:
            - containerPort: 5000
          env:
            - name: GUNICORN_CMD_ARGS
              value: "--forwarded-allow-ips=*"
            - name: MLFLOW_DISABLE_HOSTNAME_VALIDATION
              value: "true"
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.s3.region }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}