FROM python:3.10-slim

WORKDIR /app

COPY requirements/requirements.ml.txt .

RUN pip install torch --index-url https://download.pytorch.org/whl/cpu
RUN pip install -r requirements.ml.txt

COPY src/app/main.py .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]