FROM python:3.10-slim

WORKDIR /app

COPY requirements/requirements.evidently.txt .
RUN pip install -r requirements.evidently.txt

COPY data/processed/train.csv /app/data/train.csv
COPY src/evidently/main.py .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]